# Drupal with PostgreSQL
# Access via `http://localhost:8080`

version: '2'

services:
    drupi:
        build:
            dockerfile: Dockerfile
            context: .
        image: custom-drupal
        ports:
            - '8080:80'
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-themes:/var/www/html/themes
            - drupal-sites:/var/www/html/sites

    psql:
        image: postgres:12.1
        environment:
            POSTGRES_PASSWORD: pass
        volumes:
            - drupal-data:/var/lib/postgresql/data

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-themes:
    drupal-sites:
    drupal-data:
